### ISSUE TITLE
Image order by filename is not preserved

### ISSUE THREAD

**Issue by tombrossman** [callmeed/jekyll-image-set#3] opened 2014-08-25 15:14 UTC
Just tested this and it worked very well except that the output has the images in no particular order.

For example, if I have images DSC_0001, DSC_0002, and DSC_0003, I'd like the output to display them in that same order on the page. That isn't happening. Images appear out of order on the final page.

Is there an easy fix or a workaround? Total noob with Ruby here so apologies if this is something simple I've overlooked.

**Comment by mijndert** [comment] 2016-02-25 09:14
Hi Tom,

Did you ever find a fix for this? Thanks.

**Comment by tombrossman** [comment] 2016-02-25 09:19
No, sorry. I had been using [Sigal](https://github.com/saimn/sigal) which preserves the image order but was hoping to switch to something simpler. Haven't had time to figure this out yet.

**Comment by mijndert** [comment] 2016-02-25 09:20
No worries. Thanks for the quick reply!

**Comment by callmeed** [comment] 2016-02-25 17:37
Ok, I couldn't reproduce this but I'm sure it's very OS-specific. This commit explicitly calls #sort on the file array. Seems to solve it. 

https://github.com/callmeed/jekyll-image-set/commit/6fce29f29193beae733f8c70ac027c7db6a9e13e

**Closed by callmeed** 2016-02-25 17:37 UTC
